# Generated by Django 3.2.4 on 2021-07-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews_about_service',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=155, verbose_name='Фамилия пользователя')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок отзыва')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Отзыв о сервисе',
                'verbose_name_plural': 'Отзывы о сервисе',
            },
        ),
    ]
